language: ruby

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_3.2.gemfile

# Just doing what I'm told https://github.com/grosser/wwtd
bundler_args: "--no-deployment"

addons:
  code_climate:
    repo_token: b96d4021e601491d9aae499b7658f1701f7af63de2ed3152d868f4df14b43fc2

matrix:
  allow_failures:
    - env: RAILS_VERSION=master
    - rvm: ruby-head

before_install:
  - sudo apt-get update
  - sudo apt-get install libpython2.7 python-pygments

before_script:
  # Ensure the MySQL DB Exists
  - mysql -e 'create database blogit_app_test'
  - psql -c 'create database blogit_app_test' -U postgres

script: "rake spec"