language: ruby


env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"
  - DB=sqlite 
  - DB=mysql 
  - DB=postgresql
  
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
        
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  
before_script: 
  - mysql -e 'create database blogit_app_test' 
  - psql -c 'create database blogit_app_test' -U postgres